### ISSUE TITLE
Download only specific stations (--identity flag)

### ISSUE THREAD

**Issue by kasra-hosseini** [kasra-hosseini/obspyDMT#12]
John's comment:
***it would be nice to download accordant events of a couple of stations. You are right, this works for e.g: "--identity YV.RR*.*.*"
But it does not for: "--identity YV.[EURO|MAYO].*.*"
It would be somehow nice to make the full regex available to that option (or is it already, didn't work for me)***

***
This works for --sta flag but not for --identity.

**Comment by john-robert** [comment]
I just noted if I use:

``` ... --net YV  --sta EURO```

the download, storing and correction works just fine. However, using:

``` ... --net YV  --sta EURO,RR52,MAYO ```

all downloads and storings of data work correctly but the following error is raised:

> *****************************
FDSN -- Instrument Correction
*****************************
There is no station in the directory to correct!
Address: /home/john/Desktop/2013-06-02_2013-06-02_6.2_6.2/20130602_26


So there obviously is no correction taking place although everything is absolutely as it should. Can one confirm that?

**Comment by kasra-hosseini** [comment]
This problem seems to be solved as I checked the following command line and it works fine:

```python
$ obspyDMT --datapath test_two_stations --continuous --min_date 2013-01-01-01-00-00 --max_date 2013-01-01-03-00-00 --net TA --cha BHZ --sta 058A,059A
```

Please re-open this issue in case that the problem is still there for some cases.
