### ISSUE TITLE
Instrument correction seperate from downloading

### ISSUE THREAD

**Issue by john-robert** [kasra-hosseini/obspyDMT#19]
To apply the instrument correction of separately downloaded files, I use the following command:
```
obspyDMT --ic_all '/Users/.../2012-10-08_2013-11-28/' --corr_unit 'DIS'
```
I receive the following error message (although all paths and whatsoever are ok):
> ...  
There is no station in the directory to correct!
Address: /Users/john/Desktop/insu_dis/2012-10-08_2013-11-28/20121008_71
There is no station in the directory to correct!
Address: /Users/john/Desktop/insu_dis/2012-10-08_2013-11-28/20121009_70
There is no station in the directory to correct!
...

for all the accordant folders, both for 'IRIS' & 'arc' Instrument Correction.

The problem is, I downloaded data from RESIF using obspyDMT. In the all the station_event files in the info folder, the last entry is hence ',RESIF'.

Checking the code in **instrumend_handler.py**, none of the conditions in line 77 or 83 is fulfilled, as 'clients' is either 'arc' or 'IRIS'.  
Because these conditions are not fulfilled, 'ls_saved_stas_tmp' is not filled properly and the loop from line 95 on leads finally to an empty 'ls_saved_stas' and thus to the seen output.

I don't fully understand why it is like this, neither I would like to find the solution as I am a bit lost in the new code structure.

However, **workaround** would be looping over each station_event file and changing ',RESIF' to e.g. ',IRIS'. This works.

**Comment by kasra-hosseini** [comment]
@john-robert Thanks for reporting this. Can you check the following command line:

```python
obspyDMT --ic_all '/Users/.../2012-10-08_2013-11-28/' --corr_unit 'DIS' --fdsn_base_url 'all_fdsn'
```

Basically adding the following option:
```python
--fdsn_base_url 'all_fdsn'
```

Does this flag do the job?

Cheers,
K.

**Comment by john-robert** [comment]
Yes, it does do the job then !
Alternatively:
```
--fds_base_url 'RESIF'
```
works as well.
That's nice, maybe it would be a good thing to mention it in obspyDMT README.md.

Thanks for your help, once again. :)

**Comment by kasra-hosseini** [comment]
That should be definitely included in the obspyDMT README. I actually forgot to do that.

My pleasure John...thanks for reporting the new solutions/difficulties/bugs...they are very helpful.
