### ISSUE TITLE
ArcLink for restricted data download issues

### ISSUE THREAD

**Issue by mary-tsekhmistrenko** [kasra-hosseini/obspyDMT#26]
ArcLink for a request of restricted data was not working properly because obspyDMT is hard coded in two parts:
- data_handler.py around line 440 and metadata_handler.py around line 244:
  client_arclink = Client_arclink(user='email_address@arclink.de'
                                                           timeout=input_dics['arc_wave_timeout'],
                                                           dcid_key_file='dcidpasswords.txt')

The email address was fixed and it's not possible to put a flag in the command line for eg. arclink_email, also for restricted data it needs a password in a specific format. Instead of putting the password in a file you could also use Client_arclink(... dcid_keys={password}). But this also needs a new flag for the command line, eg arclink_dcid. This password is needed for encrypting the downloaded data. 

After these few modification it should work again. 

P.S.: The firewall of you institute might also cause some problems, access was denied until I went around it.

**Comment by kasra-hosseini** [comment]
Deprecated (see v2.2.8)
