### ISSUE TITLE
Trouble during quick-tour

### ISSUE THREAD

**Issue by funkes** [kasra-hosseini/obspyDMT#34]
First impression of obspyDMT is great - many thanks!

But during quick tour 2 times I got trouble:
* Access to USGS catalogue only works after chaning "--event_catalog NEIC_USGS" to "--event_catalog USGS" on topics "Earthquake meta-data" and "Seismicity map".
* Plotting of focal mechanisms resp. moment tensors fails on topics "Earthquake meta-data" and "Event-based mode. But omitting "--plot_focal" creates more or less correct plots, but only with colored circles in place of beach balls.

What could I do better?
Is here the right place for such user trouble?
Do you need more details?
```
~$ obspyDMT --check
[...]
********************************
Check all the BASIC dependencies
********************************
=================================
obspy ver: 1.0.3
numpy ver: 1.11.0
scipy ver: 0.17.0
matplotlib ver: 1.5.1
Basemap ver: 1.0.7
=================================
~$ 
```
All other tested steps work fine.

**Comment by kasra-hosseini** [comment]
> First impression of obspyDMT is great - many thanks!
- Thanks!

> Is here the right place for such user trouble?
- Yes!

> Plotting of focal mechanisms resp. moment tensors fails on topics "Earthquake meta-data" and "Event-based mode. But omitting "--plot_focal" creates more or less correct plots, but only with colored circles in place of beach balls.
- ``--plot_focal`` needs the moment tensor information (while ``--plot_event`` needs only the event location), and apparently, moment tensors could not be downloaded using ``--event_catalog NEIC_USGS`` in the previous step. Once the problem with this is solved, you should be able to plot the beach-ball as well.

> Do you need more details?
- Can you please send the command line and the error message?

I just checked the following command (python 2.7 and python 3.5):

```
obspyDMT --datapath neic_event_metadata --min_mag 5.5 --min_date 2014-01-01 --max_date 2015-01-01 --event_catalog NEIC_USGS --event_info
```

Followed by:
```
obspyDMT --datapath neic_event_metadata --local --plot_ev --plot_focal
```
and I could generate:
![event_station](https://user-images.githubusercontent.com/1899856/32113876-9d696524-bb39-11e7-8868-4c24da1d0928.png)

(Note: This is not exactly the same as the example in [Earthquake meta-data](https://github.com/kasra-hosseini/obspyDMT#earthquake-meta-data) because it contains only events in 2014.)

**Comment by funkes** [comment]
Thanks for fast reaction last friday!

> --plot_focal needs the moment tensor information (while --plot_event needs only the event location), and apparently, moment tensors could not be downloaded using --event_catalog NEIC_USGS in the previous step. 

This isn't exactly, what I would report: My first topic is "--event_catalog NEIC_USGS" don't work, but "--event_catalog USGS" works. Here some copies from my command line:

- Create an empty directory:
```
sfunke@sfunke-HP-ProBook:~/sandbox$ 
sfunke@sfunke-HP-ProBook:~/sandbox$ ll
insgesamt 8
drwxrwxr-x  2 sfunke sfunke 4096 Okt 30 11:08 ./
drwxr-xr-x 78 sfunke sfunke 4096 Okt 30 11:08 ../
sfunke@sfunke-HP-ProBook:~/sandbox$ 
```
- Try your test call using "--event_catalog NEIC_USGS":
```
sfunke@sfunke-HP-ProBook:~/sandbox$ 
sfunke@sfunke-HP-ProBook:~/sandbox$ obspyDMT --datapath neic_event_metadata --min_mag 5.5 --min_date 2014-01-01 --max_date 2015-01-01 --event_catalog NEIC_USGS --event_info
--------------------------------------------------------------------------------
		   obspyDMT (obspy Data Management Tool)

	Python Toolbox for Retrieving, Processing and Management of
			Large Seismological Datasets

:copyright:
The ObsPy Development Team (devs@obspy.org)

Developed by Kasra Hosseini
email: kasra.hosseinizad@earth.ox.ac.uk

:license:
GNU General Public License, Version 3
(http://www.gnu.org/licenses/gpl-3.0-standalone.html)
--------------------------------------------------------------------------------

obspyDMT primary mode: event_based

Event(s) are based on:	NEIC_USGS
#Divisions: 12
1,------------------------------------------------------------
[WARNING] local variable 'remotefile' referenced before assignment
------------------------------------------------------------

#Events after filtering: 0

==================================================
obspyDMT main program has finished!

Info:
* The directory contains 0.004 MB of data.
/home/sfunke/sandbox/neic_event_metadata
* Total time of execution: 0:00:00 (h:m:s)
==================================================

sfunke@sfunke-HP-ProBook:~/sandbox$ 
```
* Replace "--event_catalog NEIC_USGS" by "--event_catalog USGS" an repeat last command:
```sfunke@sfunke-HP-ProBook:~/sandbox$ 
sfunke@sfunke-HP-ProBook:~/sandbox$ obspyDMT --datapath neic_event_metadata --min_mag 5.5 --min_date 2014-01-01 --max_date 2015-01-01 --event_catalog USGS --event_info

--------------------------------------------------------------------------------
		   obspyDMT (obspy Data Management Tool)

	Python Toolbox for Retrieving, Processing and Management of
			Large Seismological Datasets

:copyright:
The ObsPy Development Team (devs@obspy.org)

Developed by Kasra Hosseini
email: kasra.hosseinizad@earth.ox.ac.uk

:license:
GNU General Public License, Version 3
(http://www.gnu.org/licenses/gpl-3.0-standalone.html)
--------------------------------------------------------------------------------

obspyDMT primary mode: event_based

Event(s) are based on:	USGS

#N   LAT       LON       DEP  DATETIME             MAG   AUTH  EV_ID              FLY  
--------------------------------------------------------------------------------
1      13.748   120.667  110  2014-12-31T09:26:22  5.5   None  20141231_092622.a  NAN
2      -4.438   144.002  123  2014-12-31T01:37:33  5.8   None  20141231_013733.a  NAN
3     -20.326  -178.564  599  2014-12-30T21:17:23  6.0   None  20141230_211723.a  NAN
..
478    36.970   143.382  22   2014-01-04T05:23:00  5.5   None  20140104_052300.a  NAN
479   -20.687   -70.795  26   2014-01-04T00:11:48  5.7   None  20140104_001148.a  NAN
480   -13.863   167.249  187  2014-01-01T16:03:29  6.5   None  20140101_160329.a  NAN
--------------------------------------------------------------------------------

Number of events/intervals: 480
Time for retrieving and saving the event info: 0:00:09

#Events after filtering: 480

==================================================
obspyDMT main program has finished!

Info:
* The directory contains 1.663 MB of data.
/home/sfunke/sandbox/neic_event_metadata
* Total time of execution: 0:00:11 (h:m:s)
==================================================

sfunke@sfunke-HP-ProBook:~/sandbox$ 
```
Only second call was more or less successfullly.

As second topic the problem with beach-balls persists:

> Once the problem with this is solved, you should be able to plot the beach-ball as well.

After mentioned download of 480 event meta-data I try to plot seismicity map in two versions:
* With "--plot_focal" I get error messages (probaly 480 times):
```
sfunke@sfunke-HP-ProBook:~/sandbox$ 
sfunke@sfunke-HP-ProBook:~/sandbox$ obspyDMT --datapath neic_event_metadata --local --plot_ev --plot_focal

--------------------------------------------------------------------------------
		   obspyDMT (obspy Data Management Tool)

	Python Toolbox for Retrieving, Processing and Management of
			Large Seismological Datasets

:copyright:
The ObsPy Development Team (devs@obspy.org)

Developed by Kasra Hosseini
email: kasra.hosseinizad@earth.ox.ac.uk

:license:
GNU General Public License, Version 3
(http://www.gnu.org/licenses/gpl-3.0-standalone.html)
--------------------------------------------------------------------------------

############################################################
WARNING: --min_date is set to 1970-01-01T00:00:00.000000Z
WARNING: --min_mag is set to 3.0
############################################################

obspyDMT primary mode: local

=========================================================
use the local files:
/home/sfunke/sandbox/neic_event_metadata/EVENTS-INFO/event_list_pickle
=========================================================

#N   LAT       LON       DEP  DATETIME             MAG   AUTH  EV_ID              FLY  
--------------------------------------------------------------------------------
1      13.748   120.667  110  2014-12-31T09:26:22  5.5   None  20141231_092622.a  NAN
2      -4.438   144.002  123  2014-12-31T01:37:33  5.8   None  20141231_013733.a  NAN
3     -20.326  -178.564  599  2014-12-30T21:17:23  6.0   None  20141230_211723.a  NAN
..
478    36.970   143.382  22   2014-01-04T05:23:00  5.5   None  20140104_052300.a  NAN
479   -20.687   -70.795  26   2014-01-04T00:11:48  5.7   None  20140104_001148.a  NAN
480   -13.863   167.249  187  2014-01-01T16:03:29  6.5   None  20140101_160329.a  NAN
--------------------------------------------------------------------------------

Number of events/intervals: 480
Time for retrieving and saving the event info: 0:00:01

#Events after filtering: 480
choose the map style:
1. bluemarble (PIL should be installed)
2. etopo (PIL should be installed)
3. shadedrelief (PIL should be installed)
4. simple
4
[ERROR] moment tensor does not exist!
[ERROR] moment tensor does not exist!
[ERROR] moment tensor does not exist!
[...]
```
I got an empty World map.
* Without "--plot_focal" I don't get errors but also I don't get beach-balls:
```
sfunke@sfunke-HP-ProBook:~/sandbox$ 
sfunke@sfunke-HP-ProBook:~/sandbox$ obspyDMT --datapath neic_event_metadata --local --plot_ev

--------------------------------------------------------------------------------
		   obspyDMT (obspy Data Management Tool)

	Python Toolbox for Retrieving, Processing and Management of
			Large Seismological Datasets

:copyright:
The ObsPy Development Team (devs@obspy.org)

Developed by Kasra Hosseini
email: kasra.hosseinizad@earth.ox.ac.uk

:license:
GNU General Public License, Version 3
(http://www.gnu.org/licenses/gpl-3.0-standalone.html)
--------------------------------------------------------------------------------

############################################################
WARNING: --min_date is set to 1970-01-01T00:00:00.000000Z
WARNING: --min_mag is set to 3.0
############################################################

obspyDMT primary mode: local

=========================================================
use the local files:
/home/sfunke/sandbox/neic_event_metadata/EVENTS-INFO/event_list_pickle
=========================================================

#N   LAT       LON       DEP  DATETIME             MAG   AUTH  EV_ID              FLY  
--------------------------------------------------------------------------------
1      13.748   120.667  110  2014-12-31T09:26:22  5.5   None  20141231_092622.a  NAN
2      -4.438   144.002  123  2014-12-31T01:37:33  5.8   None  20141231_013733.a  NAN
3     -20.326  -178.564  599  2014-12-30T21:17:23  6.0   None  20141230_211723.a  NAN
..
478    36.970   143.382  22   2014-01-04T05:23:00  5.5   None  20140104_052300.a  NAN
479   -20.687   -70.795  26   2014-01-04T00:11:48  5.7   None  20140104_001148.a  NAN
480   -13.863   167.249  187  2014-01-01T16:03:29  6.5   None  20140101_160329.a  NAN
--------------------------------------------------------------------------------

Number of events/intervals: 480
Time for retrieving and saving the event info: 0:00:01

#Events after filtering: 480
choose the map style:
1. bluemarble (PIL should be installed)
2. etopo (PIL should be installed)
3. shadedrelief (PIL should be installed)
4. simple
4

==================================================
obspyDMT main program has finished!

Info:
* The directory contains 1.663 MB of data.
/home/sfunke/sandbox/neic_event_metadata
* Total time of execution: 0:00:21 (h:m:s)
==================================================

sfunke@sfunke-HP-ProBook:~/sandbox$ 
```
Except for missing beach-balls (replaced by blue filled circles) World map shows expected events.

**Comment by funkes** [comment]
I forgot: I'm using python 2.7:
```
sfunke@sfunke-HP-ProBook:~/sandbox$ 
sfunke@sfunke-HP-ProBook:~/sandbox$ python --version
Python 2.7.12
sfunke@sfunke-HP-ProBook:~/sandbox$ 
```

**Comment by kasra-hosseini** [comment]
> This isn't exactly, what I would report: My first topic is "--event_catalog NEIC_USGS" don't work, but "--event_catalog USGS" works. Here some copies from my command line:

Sorry, I should have said this before that the only two catalogs that provide moment-tensor information are `NEIC_USGS` and `GCMT_COMBO`. Please note that `--event_catalog NEIC_USGS` downloads the event information directly from the USGS catalog while `--event_catalog USGS` uses `obspy.clients.fdsn` to do so. The reason for this duplication is that the former (`--event_catalog NEIC_USGS`)  can download moment tensor information while the latter (`--event_catalog USGS`) can not do that. Consequently, when you use `--event_catalog USGS`, you can not plot the beachballs, and I hope/expect that if the problem with `--event_catalog NEIC_USGS` is solved, beachballs can be plotted as well. I totally see that having two different names: `NEIC_USGS` and `USGS` for one catalog is confusing and maybe I should change that, but does the explanation make sense?

Which version of obspyDMT are you using?
```
obspyDMT --version
``` 
Would you please check the following URL in your **browser**:

```
http://earthquake.usgs.gov/fdsnws/event/1/query.quakeml?includeallorigins=true&starttime=2014-01-01T00%3A00%3A00.000000Z&minmagnitude=5.5&mindepth=-10.0&maxmagnitude=10.0&maxdepth=6000.0&producttype=moment-tensor&endtime=2014-01-31T00%3A00%3A00.000000Z&includeallmagnitudes=true
```

Do you see something similar to:
![screen shot 2017-10-30 at 13 20 40](https://user-images.githubusercontent.com/1899856/32172931-3b3b211a-bd75-11e7-866a-9eb76b2aa22b.png)


Moreover, what do you exactly mean by more or less?
> Only second call was more or less successfullly.

**Comment by funkes** [comment]
Trying to write a ne comment, unfortunately I run into new trouble - see issue #36.

Sorry for new questions...

But a few requested answers:
> Moreover, what do you exactly mean by more or less?
> > Only second call was more or less successfullly.
It was successfully to get an epicenter map, but not successfully because of missing beach balls.

```
sfunke@sfunke-HP-ProBook:~/sandbox2$ 
sfunke@sfunke-HP-ProBook:~/sandbox2$ obspyDMT --version
Traceback (most recent call last):
  File "/usr/local/bin/obspyDMT", line 7, in <module>
    from obspyDMT.obspyDMT import main
  File "/usr/local/lib/python2.7/dist-packages/obspyDMT/obspyDMT.py", line 18, in <module>
    from .utils.data_handler import get_data
  File "/usr/local/lib/python2.7/dist-packages/obspyDMT/utils/data_handler.py", line 40, in <module>
    from .utility_codes import calculate_time_phase, getFolderSize
  File "/usr/local/lib/python2.7/dist-packages/obspyDMT/utils/utility_codes.py", line 35, in <module>
    from obspy.taup.taup import getTravelTimes
ImportError: No module named taup
sfunke@sfunke-HP-ProBook:~/sandbox2$ 
```
Actual see #36, but on Friday the answer was:
```
~$ obspyDMT --check
[...]
********************************
Check all the BASIC dependencies
********************************
=================================
obspy ver: 1.0.3
numpy ver: 1.11.0
scipy ver: 0.17.0
matplotlib ver: 1.5.1
Basemap ver: 1.0.7
=================================
~$ 
```

Calling http://earthquake.usgs.gov/fdsnws/event/1/query.quakeml?includeallorigins=true&starttime=2014-01-01T00%3A00%3A00.000000Z&minmagnitude=5.5&mindepth=-10.0&maxmagnitude=10.0&maxdepth=6000.0&producttype=moment-tensor&endtime=2014-01-31T00%3A00%3A00.000000Z&includeallmagnitudes=true by web browser I get a long xml output; first screen looks like your example.

**Comment by kasra-hosseini** [comment]
Please update your obspyDMT, I wrote a comment [here](https://github.com/kasra-hosseini/obspyDMT/issues/36).

**Comment by funkes** [comment]
> Please update your obspyDMT, I wrote a comment here.

Successfully done, see issue #36.

> Sorry, I should have said this before that the only two catalogs that provide moment-tensor information are NEIC_USGS and GCMT_COMBO. 

O.k., if I want to play with moment tensors/beach balls only catalogs NEIC_USGS and GCMT_COMBO are useful.

> [...] and I hope/expect that if the problem with --event_catalog NEIC_USGS is solved, beachballs can be plotted as well. 

Where could the problem with --event_catalog NEIC_USGS situated, locally on my site, or far by NEIC, or in obspyDMT's code? Should I wait or can I do something?

> Consequently, when you use --event_catalog USGS, you can not plot the beachballs, I totally see that having two different names: NEIC_USGS and USGS for one catalog is confusing and maybe I should change that, but does the explanation make sense?

Yes; thanks for clarification.

> Which version of obspyDMT are you using?

Now it should be actually: 
```
		*********************************
		*        obspyDMT version:      *
		*	     2.0.5		*
		*********************************
```

Playing with GCMT_COMBO catalog a new question arises: Calling inside an empty data directory it seems, that new catalog should be written not to data path but to path of executables:

```
sfunke@sfunke-HP-ProBook:~/sandbox2$ 
sfunke@sfunke-HP-ProBook:~/sandbox2$ obspyDMT --datapath neic_event_metadata --min_mag 5.5 --min_date 2014-01-01 --max_date 2015-01-01 --event_catalog GCMT_COMBO --event_info
--------------------------------------------------------------------------------
		   obspyDMT (obspy Data Management Tool)

	Python Toolbox for Retrieving, Processing and Management of
			Large Seismological Datasets

:copyright:
The ObsPy Development Team (devs@obspy.org)

Developed by Kasra Hosseini
email: kasra.hosseinizad@earth.ox.ac.uk

:license:
GNU General Public License, Version 3
(http://www.gnu.org/licenses/gpl-3.0-standalone.html)
--------------------------------------------------------------------------------

obspyDMT primary mode: event_based

Event(s) are based on:	GCMT_COMBO
------------------------------------------------------------
[WARNING] [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/obspyDMT/gcmt_catalog'
------------------------------------------------------------

#Events after filtering: 0

==================================================
obspyDMT main program has finished!

Info:
* The directory contains 0.004 MB of data.
/home/sfunke/sandbox2/neic_event_metadata
* Total time of execution: 0:00:00 (h:m:s)
==================================================

sfunke@sfunke-HP-ProBook:~/sandbox2$ 
```

**Comment by kasra-hosseini** [comment]
> Where could the problem with --event_catalog NEIC_USGS situated, locally on my site, or far by NEIC, or in obspyDMT's code? Should I wait or can I do something?

It is difficult to say, really. However, given that I have tried the following command line on different machines using different python versions (of course, by using a clean [not modified] version of obspyDMT) and it has literally worked on all cases, I think the problem might be from your local connection (e.g., firewall, ...).

```
obspyDMT --datapath neic_event_metadata --min_mag 5.5 --min_date 2014-01-01 --max_date 2015-01-01 --event_catalog NEIC_USGS --event_info
```

To test this, please run the following code on your machine and check the output:
```python
try:
        from urllib2 import urlopen
except ImportError:
        from urllib.request import urlopen

remotefile = 'http://earthquake.usgs.gov/fdsnws/event/1/query.quakeml?includeallorigins=true&starttime=2014-01-01T00%3A00%3A00.000000Z&minmagnitude=5.5&mindepth=-10.0&maxmagnitude=10.0&maxdepth=6000.0&producttype=moment-tensor&endtime=2014-01-31T00%3A00%3A00.000000Z&includeallmagnitudes=true'
page = urlopen(remotefile)
page_content = page.read()
page_content = page_content.decode("utf-8")
print(page_content[0:500])
```

The above snippet is an example of what obspyDMT does internally for NEIC_USGS. The output that I get is:

```
<?xml version="1.0" encoding="UTF-8"?>
<q:quakeml xmlns="http://quakeml.org/xmlns/bed/1.2" xmlns:anss="http://anss.org/xmlns/event/0.1" xmlns:catalog="http://anss.org/xmlns/catalog/0.1" xmlns:q="http://quakeml.org/xmlns/quakeml/1.2">
<eventParameters publicID="quakeml:earthquake.usgs.gov/fdsnws/event/1/query.quakeml?includeallorigins=true&amp;starttime=2014-01-01T00%3A00%3A00.000000Z&amp;minmagnitude=5.5&amp;mindepth=-10.0&amp;maxmagnitude=10.0&amp;maxdepth=6000.0&amp;producttype=moment-tensor&a
```

> Playing with GCMT_COMBO catalog a new question arises: Calling inside an empty data directory it seems, that new catalog should be written not to data path but to path of executables:

In case of GCMT_COMBO catalog, DMT tries to create a "local" data set, so the following requests would be much faster. It creates this dataset in the obspyDMT parent dir. However, this is not that user-friendly, and obviously it does not work when you do not have a write permission! I should change this so one can select the gcmt_data_path. I will try to implement it until tomorrow, and I will write you back.

**Comment by funkes** [comment]
> I think the problem might be from your local connection (e.g., firewall, ...).

Hm...

> To test this, please run the following code on your machine and check the output:
> [...]
> The above snippet is an example of what obspyDMT does internally for NEIC_USGS. The output that I get is:

I get exactly the same output.

>> Playing with GCMT_COMBO catalog a new question arises: 
>
> In case of GCMT_COMBO catalog, DMT tries to create a "local" data set, so the following requests would be much faster. 

Sounds well!

> It creates this dataset in the obspyDMT parent dir. However, this is not that user-friendly, and obviously it does not work when you do not have a write permission! I should change this so one can select the gcmt_data_path. I will try to implement it until tomorrow, and I will write you back.

Thanks for this announcment! In meanwhile I played a little with write permissions - see new forked issue #37.

**Comment by kasra-hosseini** [comment]
@funkes Sorry for the delayed response (I was on a trip last week)!

Firstly, does the following command line work for you now?

```
obspyDMT --datapath neic_event_metadata --min_mag 5.5 --min_date 2014-01-01 --max_date 2015-01-01 --event_catalog NEIC_USGS --event_info
```

if not (which I assume that it is the case), I would suggest that we install the obspyDMT with the following method:

[2. install obspyDMT from the source code](https://github.com/kasra-hosseini/obspyDMT#installation)

using the second method (```2. install obspyDMT from the source code```).

For ```/path/to/my/obspyDMT``` which is mentioned in the tutorial, please choose something on your $HOME directory, e.g., ~/local/obspyDMT.

Please make sure that you first remove your current obspyDMT (you can check the current one by: ```which obspyDMT``` [linux and Mac]).

If this solves this problem, I expect that the other issue #37  will be solved as well.

**Comment by funkes** [comment]
I don't know why, first command works now and found 450 events:

```
sfunke@sfunke-HP-ProBook:~$ obspyDMT --datapath neic_event_metadata --min_mag 5.5 --min_date 2014-01-01 --max_date 2015-01-01 --event_catalog NEIC_USGS --event_info
[...]
--------------------------------------------------------------------------------

obspyDMT primary mode: event_based

Event(s) are based on:	NEIC_USGS
#Divisions: 12
1,2,3,4,5,6,7,8,9,10,11,12,
Assembling 13 xml files...
1,2,3,4,5,6,7,8,9,10,11,12,13,
cleaning up the temporary folder.

37.907774 sec to retrieve the event info form NEIC.

#N   LAT       LON       DEP  DATETIME             MAG   AUTH  EV_ID              FLY  
--------------------------------------------------------------------------------
1      13.748   120.667  110  2014-12-31T09:26:22  5.5   None  20141231_092622.a  NAN
2      -4.438   144.002  123  2014-12-31T01:37:33  5.8   None  20141231_013733.a  NAN
3     -20.326  -178.564  599  2014-12-30T21:17:23  6.0   None  20141230_211723.a  NAN
..
448    36.970   143.382  22   2014-01-04T05:23:00  5.5   None  20140104_052300.a  NAN
449   -20.687   -70.795  26   2014-01-04T00:11:48  5.7   None  20140104_001148.a  NAN
450   -13.863   167.249  187  2014-01-01T16:03:29  6.5   None  20140101_160329.a  NAN
--------------------------------------------------------------------------------

Number of events/intervals: 450
Time for retrieving and saving the event info: 0:00:41

#Events after filtering: 450

==================================================
obspyDMT main program has finished!

Info:
* The directory contains 6.388 MB of data.
/home/sfunke/neic_event_metadata
* Total time of execution: 0:00:47 (h:m:s)
==================================================

sfunke@sfunke-HP-ProBook:~$ 
```

>  If this solves this problem, I expect that the other issue #37 will be solved as well.

Yes, I closed it.

Many thanks! From my point of view you can close this issue #34 too.

**Comment by kasra-hosseini** [comment]
Great! I am happy that is working now. Please let me know if the problem persists.
