### ISSUE TITLE
Every call of obspyDMT crashes

### ISSUE THREAD

**Issue by funkes** [kasra-hosseini/obspyDMT#36]
During discussion #34 "Trouble during quick-tour" all newer attempts to run obspyDMT commands quickly end in error line "ImportError: No module named taup":

To avoid some interferences I created a new empty directory and call again "obspyDMT --tour":
```
sfunke@sfunke-HP-ProBook:~/sandbox2$ 
sfunke@sfunke-HP-ProBook:~/sandbox2$ obspyDMT --tour
Traceback (most recent call last):
  File "/usr/local/bin/obspyDMT", line 7, in <module>
    from obspyDMT.obspyDMT import main
  File "/usr/local/lib/python2.7/dist-packages/obspyDMT/obspyDMT.py", line 18, in <module>
    from .utils.data_handler import get_data
  File "/usr/local/lib/python2.7/dist-packages/obspyDMT/utils/data_handler.py", line 40, in <module>
    from .utility_codes import calculate_time_phase, getFolderSize
  File "/usr/local/lib/python2.7/dist-packages/obspyDMT/utils/utility_codes.py", line 35, in <module>
    from obspy.taup.taup import getTravelTimes
ImportError: No module named taup
sfunke@sfunke-HP-ProBook:~/sandbox2$ 
```
There are few strange facts:
- This and other commands worked fine on Friday.
- Today I played with ObsPy on python's command line, but:
- I didn't changed installation or configuration of ObsPy (at least not intensionally).
- Reboot of my Ubuntu box don't help.
- No other problems on my Ubuntu box are to be seen.

**Comment by kasra-hosseini** [comment]
Thanks for reporting this. The new version of obspy was released 2-3 days ago, and there was one part of obspyDMT that was not compatible with the newest version, see [this commit](https://github.com/kasra-hosseini/obspyDMT/commit/6806616930bc75149e88ca3aea58c2fccdd98515). Please update your obspyDMT and check the above command again. The new version is (`obspyDMT --version`): 2.0.5

**Comment by funkes** [comment]
> Please update your obspyDMT and check the above command again. The new version is (obspyDMT --version): 2.0.5

Thanks for the useful hint. After successful update to obspyDMT_2.0.5 general crashes of obspyDMT commands disappear!
