### ISSUE TITLE
Event finding fails.

### ISSUE THREAD

**Issue by rsmith100** [kasra-hosseini/obspyDMT#38]
Hi,

Firstly obspyDMT is great and I love it!

I have recently run into a problem where I am running the a command that I have previously ran with no issues with an updated event time window. I get this message:

WARNING: 
Exception AttributeError: "'ResourceIdentifier' object has no attribute 'fixed'" in <object repr() failed> ignored

#Events after filtering: 0
The command is:
obspyDMT --datapath iris_events_dir --min_date 2000-01-01 --max_date 2010-01-01 --min_depth 100.0 --min_mag 6.0 --cha BHZ --station_rect -130/91/38/79 --event_circle 63/35/50/140 --preset 500 --offset 3600 --instrument_correction --syngine --syngine_bg_model prem_a_2s --req_parallel --req_np 2

It used to pull the data no problem and I can't see anything wrong with this new updated request(  I have only changed the max_date). I have tried to run the old command that did work and everything just brings up this problem. Any thoughts on how to solve the problem?

Thanks!

**Comment by kasra-hosseini** [comment]
Hi @rsmith100,

Thanks for your kind comment. Your command seems fine as I also tried the same command line on my local computer:

`
obspyDMT --datapath iris_events_dir --min_date 2000-01-01 --max_date 2010-01-01 --min_depth 100.0 --min_mag 6.0 --cha BHZ --station_rect -130/91/38/79 --event_circle 63/35/50/140 --preset 500 --offset 3600 --instrument_correction --syngine --syngine_bg_model prem_a_2s --req_parallel --req_np 2
`

and here is the output:

```
obspyDMT primary mode: event_based

[WARNING] no local event was found!
[WARNING] use IRIS catalog instead!

Event(s) are based on:	IRIS

#N   LAT       LON       DEP  DATETIME             MAG  AUTH  EV_ID              FLY
--------------------------------------------------------------------------------
1      42.237   134.772  396  2009-12-24T00:23:33  6.3  None  20091224_002333.a  NAN
2      53.399   152.798  653  2009-12-10T02:30:52  6.3  None  20091210_023052.a  NAN
3     -31.550   179.559  435  2009-11-22T22:47:27  6.2  None  20091122_224727.a  NAN
..
239   -21.127  -179.203  601  2000-01-15T12:49:43  6.0  None  20000115_124943.a  NAN
240   -17.550  -178.714  502  2000-01-13T20:07:12  6.2  None  20000113_200712.a  NAN
241   -16.855  -174.203  131  2000-01-08T16:47:14  7.2  None  20000108_164714.a  NAN
--------------------------------------------------------------------------------

Number of events/intervals: 241
Time for retrieving and saving the event info: 0:00:09

#Events after filtering: 241
```

Can you check the version of your DMT by:

```
obspyDMT --version
```

This should be 2.0.5.

**Comment by rsmith100** [comment]
Hi

So I think I solved the problem I needed to update obspyDMT. I'm not sure why though because I only installed it last week. This seems to have fixed the issue however. 

Thanks for the response though.

**Comment by kasra-hosseini** [comment]
I am not sure why that is as obspyDMT was not updated last week. One possibility is that there were two versions of DMT installed on your machine and ```update``` somehow resolved some inconsistent dependencies, but it is difficult to say. In any case, please let me know if the problem persists.
