### ISSUE TITLE
Consistency of # of events in continuous mode

### ISSUE THREAD

**Issue by ghraecakter** [kasra-hosseini/obspyDMT#45]
The number of events in continuous mode is inconsistent
for length of 1 day and multiple days.
For example, with the same start `2000-01-01`,
end `2000-01-02` yields 1 day, i.e. 1 `continuous*` directory,
while end `2000-01-03` yields 3.
This is due to that, for multiple days, an `offset` default to 1800
is considered while not for < 1 day.
A possible workaround would be to set the default of `offset`
as 0 for continuous mode.

https://github.com/kasra-hosseini/obspyDMT/blob/be6d931aaa627bbf3bb2b324b807876e3a7877bd/obspyDMT/utils/event_handler.py#L563-L604

**Comment by kasra-hosseini** [comment]
@ghraecakter many thanks for reporting this. It should be solved now: https://github.com/kasra-hosseini/obspyDMT/commit/2f0241b38279b364c91dd2ac5e420c3831c8b456
