### ISSUE TITLE
Sort help options alphabetically

### ISSUE THREAD

**Issue by john-robert** [kasra-hosseini/obspyDMT#6]
I like the help menu of obspyDMT but I personally find it annyoing to scroll down and up all the time just because I know the name of the option but not where it was placed. 
An alphabetical order would ease things and is just 10 minutes of work.

Addtionally:
- including another option to allow users to read-in an already existing event_file
- I don't understand the option "--cut_time_phase" at all. Could you explain to me what is intended and, furthermore, what is cut ? Are the given phases (P, Pdiff, PKiKP) just a collection or all available things, how are they related to that option
- I just talked to Fabrice and showed him the tool, he also likes it and has some ideas. However, he thinks a tiny example at every option would make a big difference. E.g. for event_circle do I have to put them in apostrophes or not ...

So the options maybe need some love.

**Comment by kasra-hosseini** [comment]
Hi John,

I am trying to manage the issues. What is the status for this one?

Best,
Kasra

**Comment by john-robert** [comment]
Hi Kasra,

Error: -12345
>> lazy programmer postponed sorting options. zero work accomplished.
process stucked.

**Comment by kasra-hosseini** [comment]
:D ok...that is also not the highest priority. Thanks for the update!
