### ISSUE TITLE
ArcLink protocol is officially deprecated

### ISSUE THREAD

**Issue by mary-tsekhmistrenko** [kasra-hosseini/obspyDMT#65]
Error message when obspyDMT is running:

ModuleNotFoundError: No module named 'obspy.clients.arclink'
ModuleNotFoundError: No module named 'obspy.arclink'

because of:

http://msnoise.org/obspy-doc/packages/obspy.clients.arclink.html

**Comment by kasra-hosseini** [comment]
Done in v2.2.8
